// <auto-generated />
using System;
using AdministradorSeries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdministradorSeries.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231020181252_nuevasSeries")]
    partial class nuevasSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            Nombre = "Accion"
                        },
                        new
                        {
                            Id = new Guid("ad6b15c1-f64e-4456-bf78-c30e1f24e170"),
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = new Guid("9cefec23-6507-4799-abb7-6978b1bda370"),
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ATP")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("date");

                    b.Property<Guid>("GeneroForeiKey")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estrellas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneroForeiKey");

                    b.ToTable("Series", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b5e9399-8e95-4ae8-8745-9542a01e2cc0"),
                            ATP = false,
                            Descripcion = "Johnny Bravo es muy confiado y cree que todas las mujeres lo quieren. Con su pelo largo y ropa apretada de color negro, es conocido por sus golpes de karate.",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2004, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            PrecioAlquiler = 450m,
                            Titulo = "jony bravo",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("fd0ac60d-0151-4042-8225-5aaeddbb0ded"),
                            ATP = true,
                            Descripcion = "Un valiente joven con poderes increíbles se aventura hacia un viaje místico en tierras exóticas llenas de guerreros nobles, princesas hermosas, monstruos mutantes, extraterrestres y crueles ejércitos",
                            Estado = "AC",
                            FechaEstreno = new DateTime(1996, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 450m,
                            Titulo = "Dragon Ball",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("e085a7ec-3ef9-417f-a4e4-fea803d1d0cb"),
                            ATP = true,
                            Descripcion = " En el Princenton Plainsboro de Nueva Jersey, el Dr. Gregory House, un singular genio de la medicina, se encarga de resolver casos como lo haría Sherlock Holmes. De forma astuta juega con la psicología de la Dra. Lisa Cuddy, su mejor amigo, el oncólogo James Wilson, y del resto de su equipo de trabajo",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2012, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 450m,
                            Titulo = "Dr. House",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("dd020629-9b66-4c4d-96cc-67f2279f234f"),
                            ATP = true,
                            Descripcion = " Bleach es una serie de manga y anime escrita e ilustrada por Tite Kubo. La serie narra las aventuras de Ichigo Kurosaki, un adolescente que accidentalmente absorbe los poderes de una shinigami —personificación japonesa del Dios de la muerte— llamada Rukia Kuchiki",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2001, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 500m,
                            Titulo = "Bleach",
                            estrellas = 5
                        },
                        new
                        {
                            Id = new Guid("eac07c6d-3fa8-4729-8817-c566b54e1f54"),
                            ATP = true,
                            Descripcion = "esta serie animada narra las aventuras de Naruto Uzumaki, un ninja adolescente que aspira a convertirse en Hokage -- el máximo rango ninja -- con el propósito de ser reconocido como alguien importante dentro de su aldea ",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2002, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 500m,
                            Titulo = "Naruto",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("9f2debfe-e578-484b-8172-6bda71ef8c64"),
                            ATP = true,
                            Descripcion = " El empresario Bruce Wayne se convierte en Batman por las noches para proteger a Ciudad Gótica de los criminales  ",
                            Estado = "AC",
                            FechaEstreno = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 300m,
                            Titulo = "Batman-la serie animada ",
                            estrellas = 4
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.HasOne("AdministradorSeries.Genero", "Genero")
                        .WithMany("Series")
                        .HasForeignKey("GeneroForeiKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
