// <auto-generated />
using System;
using AdministradorSeries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdministradorSeries.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231021032217_nuevoGenero")]
    partial class nuevoGenero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            Nombre = "Accion"
                        },
                        new
                        {
                            Id = new Guid("ad6b15c1-f64e-4456-bf78-c30e1f24e170"),
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = new Guid("9cefec23-6507-4799-abb7-6978b1bda370"),
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            Nombre = "Otros"
                        },
                        new
                        {
                            Id = new Guid("82937a1a-8621-44dd-a05a-1e4b721b65bd"),
                            Nombre = "Todos"
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ATP")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("date");

                    b.Property<Guid>("GeneroForeiKey")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estrellas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneroForeiKey");

                    b.ToTable("Series", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b5e9399-8e95-4ae8-8745-9542a01e2cc0"),
                            ATP = false,
                            Descripcion = "Johnny Bravo es muy confiado y cree que todas las mujeres lo quieren. Con su pelo largo y ropa apretada de color negro, es conocido por sus golpes de karate.",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2004, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            PrecioAlquiler = 450m,
                            Titulo = "jony bravo",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("fd0ac60d-0151-4042-8225-5aaeddbb0ded"),
                            ATP = true,
                            Descripcion = "Un valiente joven con poderes increíbles se aventura hacia un viaje místico en tierras exóticas llenas de guerreros nobles, princesas hermosas, monstruos mutantes, extraterrestres y crueles ejércitos",
                            Estado = "AC",
                            FechaEstreno = new DateTime(1996, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 450m,
                            Titulo = "Dragon Ball",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("e085a7ec-3ef9-417f-a4e4-fea803d1d0cb"),
                            ATP = true,
                            Descripcion = " En el Princenton Plainsboro de Nueva Jersey, el Dr. Gregory House, un singular genio de la medicina, se encarga de resolver casos como lo haría Sherlock Holmes. De forma astuta juega con la psicología de la Dra. Lisa Cuddy, su mejor amigo, el oncólogo James Wilson, y del resto de su equipo de trabajo",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2012, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 450m,
                            Titulo = "Dr. House",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("dd020629-9b66-4c4d-96cc-67f2279f234f"),
                            ATP = true,
                            Descripcion = " Bleach es una serie de manga y anime escrita e ilustrada por Tite Kubo. La serie narra las aventuras de Ichigo Kurosaki, un adolescente que accidentalmente absorbe los poderes de una shinigami —personificación japonesa del Dios de la muerte— llamada Rukia Kuchiki",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2001, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 500m,
                            Titulo = "Bleach",
                            estrellas = 5
                        },
                        new
                        {
                            Id = new Guid("eac07c6d-3fa8-4729-8817-c566b54e1f54"),
                            ATP = true,
                            Descripcion = "esta serie animada narra las aventuras de Naruto Uzumaki, un ninja adolescente que aspira a convertirse en Hokage -- el máximo rango ninja -- con el propósito de ser reconocido como alguien importante dentro de su aldea ",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2002, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 500m,
                            Titulo = "Naruto",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("9f2debfe-e578-484b-8172-6bda71ef8c64"),
                            ATP = true,
                            Descripcion = " El empresario Bruce Wayne se convierte en Batman por las noches para proteger a Ciudad Gótica de los criminales  ",
                            Estado = "AC",
                            FechaEstreno = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 300m,
                            Titulo = "Batman-la serie animada ",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("f8020cf5-1551-4545-a0f4-5b6d7a0f2c5b"),
                            ATP = true,
                            Descripcion = "Basado en la historieta escrita por Robert Kirkman, este drama crudo describe las vidas de un grupo de sobrevivientes que está siempre en movimiento en busca de un hogar seguro durante las semanas y meses de un apocalipsis zombi",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2022, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 300m,
                            Titulo = "The Walking Dead",
                            estrellas = 3
                        },
                        new
                        {
                            Id = new Guid("374d9e0d-06d2-4eef-b29a-817e27995b1d"),
                            ATP = true,
                            Descripcion = " Dexter Morgan un experto en salpicaduras de sangre que reside en Miami, no resuelve solamente casos de asesinato sino que también los comete. De hecho, él es un asesino en serie que únicamente mata a los culpables, justificando así sus acciones y su estilo de vida",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2006, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 300m,
                            Titulo = "Dexter",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("cc5dc55e-586c-4dc1-b23a-5946c4dfb437"),
                            ATP = true,
                            Descripcion = "Conocida como Los Caballeros del Zodiaco. Estos guerreros luchan del lado de la diosa griega Athena, reencarnada en la humana Saori Kido para proteger a la humanidad de las fuerzas del mal que quieren dominar la Tierra",
                            Estado = "AC",
                            FechaEstreno = new DateTime(1986, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 500m,
                            Titulo = "Saint Seiya",
                            estrellas = 5
                        },
                        new
                        {
                            Id = new Guid("37a954fc-2825-466c-bd6f-d6015f16f84b"),
                            ATP = true,
                            Descripcion = "Patrick Jane, consejero de la Agencia de Investigación de California, es conocido por sus métodos inusuales, sin contar su ex carrera como psíquico, pero el hombre tiene un récord asombroso de casos resueltos en crímenes serios utilizando poderes de observación extraordinarios",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2008, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 200m,
                            Titulo = "El mentalsita",
                            estrellas = 2
                        },
                        new
                        {
                            Id = new Guid("3619c78c-0ab0-4a9a-9a66-a376fa846d8f"),
                            ATP = true,
                            Descripcion = "un profesor de química, se convierte en fabricante de metanfetaminas después de ser diagnosticado con cáncer. Con la ayuda de su exalumno, Jesse Pinkman, se sumerge en el mundo del crimen",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 250m,
                            Titulo = "Walter White",
                            estrellas = 2
                        },
                        new
                        {
                            Id = new Guid("4612deec-8ba7-4594-832d-60451b33763d"),
                            ATP = true,
                            Descripcion = "En el continente de Westeros, nobleza, familias poderosas y criaturas míticas luchan por el control del Trono de Hierro. Traiciones, conspiraciones y batallas épicas son moneda corriente",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 350m,
                            Titulo = "Game of Thrones",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("72117e21-bc84-4981-be92-3f17e5700b79"),
                            ATP = true,
                            Descripcion = "En los años 80, un grupo de niños se enfrenta a fuerzas sobrenaturales y experimentos secretos mientras buscan a su amigo desaparecido. En su camino, descubren un mundo paralelo llamado el Mundo del Revés",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 350m,
                            Titulo = "Stranger Things",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("963bcc8e-5a48-4802-aae5-b7f78ac51e6c"),
                            ATP = true,
                            Descripcion = "La vida de la Reina Isabel II desde su ascenso al trono británico. La serie explora su reinado y los eventos históricos que ocurrieron durante su gobierno",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 350m,
                            Titulo = "The Crown",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("5430cedd-ce54-45be-ab4c-f806ece81ddc"),
                            ATP = true,
                            Descripcion = "La vida de la Reina Isabel II desde su ascenso al trono británico. La serie explora su reinado y los eventos históricos que ocurrieron durante su gobierno",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 350m,
                            Titulo = "The Crown",
                            estrellas = 4
                        },
                        new
                        {
                            Id = new Guid("41e59a8f-3af6-4f15-b9e6-8c71530e82a9"),
                            ATP = true,
                            Descripcion = "Antología que explora la relación entre la tecnología y la sociedad. Cada episodio presenta una historia independiente que examina cómo la tecnología puede afectar nuestras vidas de maneras inesperadas.",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2011, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            PrecioAlquiler = 350m,
                            Titulo = "Black Mirror",
                            estrellas = 4
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.HasOne("AdministradorSeries.Genero", "Genero")
                        .WithMany("Series")
                        .HasForeignKey("GeneroForeiKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
