// <auto-generated />
using System;
using AdministradorSeries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdministradorSeries.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231019192339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            Nombre = "Accion"
                        },
                        new
                        {
                            Id = new Guid("ad6b15c1-f64e-4456-bf78-c30e1f24e170"),
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = new Guid("9cefec23-6507-4799-abb7-6978b1bda370"),
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = new Guid("8350900d-54fe-4db1-8a77-a4fe840551a7"),
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ATP")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("date");

                    b.Property<Guid>("GeneroForeiKey")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("estrellas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneroForeiKey");

                    b.ToTable("Series", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b5e9399-8e95-4ae8-8745-9542a01e2cc0"),
                            ATP = false,
                            Descripcion = "Johnny Bravo es muy confiado y cree que todas las mujeres lo quieren. Con su pelo largo y ropa apretada de color negro, es conocido por sus golpes de karate.",
                            Estado = "AC",
                            FechaEstreno = new DateTime(2004, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeneroForeiKey = new Guid("dccfd200-b206-41d8-a01f-752cb55733a9"),
                            PrecioAlquiler = 450m,
                            Titulo = "jony bravo",
                            estrellas = 4
                        });
                });

            modelBuilder.Entity("AdministradorSeries.Serie", b =>
                {
                    b.HasOne("AdministradorSeries.Genero", "Genero")
                        .WithMany("Series")
                        .HasForeignKey("GeneroForeiKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("AdministradorSeries.Genero", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
